
import { User } from '@supabase/supabase-js';
import { Profile } from '../types';

export const MOCK_USERS: { user: User; profile: Profile }[] = [
    // ADMIN
    {
        user: { id: 'admin-id', email: 'admin@gohandymate.com', aud: 'authenticated', created_at: new Date().toISOString(), app_metadata: {}, user_metadata: { full_name: 'System Admin' } } as any,
        profile: {
            id: 'admin-id',
            email: 'admin@gohandymate.com',
            full_name: 'System Admin',
            user_role: 'handyman', // Needs to be a valid role, but internal check handles admin status
            account_status: 'active',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        } as Profile,
    },
    // HANDYMEN (4)
    {
        user: { id: 'handyman-1', email: 'jack.plumber@example.com', aud: 'authenticated', created_at: new Date().toISOString(), app_metadata: {}, user_metadata: { full_name: 'Jack Thompson' } } as any,
        profile: {
            id: 'handyman-1',
            email: 'jack.plumber@example.com',
            full_name: 'Jack Thompson',
            user_role: 'handyman',
            account_status: 'active',
            phone: '+1 555-0101',
            address: '123 Leak Lane',
            city: 'London',
            zip_code: 'NW1 6XE',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        } as Profile,
    },
    {
        user: { id: 'handyman-2', email: 'sparky.mike@example.com', aud: 'authenticated', created_at: new Date().toISOString(), app_metadata: {}, user_metadata: { full_name: 'Mike Watson' } } as any,
        profile: {
            id: 'handyman-2',
            email: 'sparky.mike@example.com',
            full_name: 'Mike Watson',
            user_role: 'handyman',
            account_status: 'active',
            phone: '+1 555-0102',
            address: '45 Voltage Ave',
            city: 'Manchester',
            zip_code: 'M1 1AE',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        } as Profile,
    },
    {
        user: { id: 'handyman-3', email: 'sarah.painter@example.com', aud: 'authenticated', created_at: new Date().toISOString(), app_metadata: {}, user_metadata: { full_name: 'Sarah Collins' } } as any,
        profile: {
            id: 'handyman-3',
            email: 'sarah.painter@example.com',
            full_name: 'Sarah Collins',
            user_role: 'handyman',
            account_status: 'active',
            phone: '+1 555-0103',
            address: '7 Canvas Road',
            city: 'Bristol',
            zip_code: 'BS1 5TY',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        } as Profile,
    },
    {
        user: { id: 'handyman-4', email: 'bob.builder@example.com', aud: 'authenticated', created_at: new Date().toISOString(), app_metadata: {}, user_metadata: { full_name: 'Bob Richards' } } as any,
        profile: {
            id: 'handyman-4',
            email: 'bob.builder@example.com',
            full_name: 'Bob Richards',
            user_role: 'handyman',
            account_status: 'active',
            phone: '+1 555-0104',
            address: '88 Foundation St',
            city: 'Birmingham',
            zip_code: 'B1 1QU',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        } as Profile,
    },
    // CONTRACTORS (2)
    {
        user: { id: 'contractor-1', email: 'build.pro@example.com', aud: 'authenticated', created_at: new Date().toISOString(), app_metadata: {}, user_metadata: { full_name: 'James Miller' } } as any,
        profile: {
            id: 'contractor-1',
            email: 'build.pro@example.com',
            full_name: 'James Miller',
            business_name: 'Pro Build Solutions',
            user_role: 'contractor',
            account_status: 'active',
            phone: '+1 555-0201',
            address: '500 Industry Way',
            city: 'Leeds',
            zip_code: 'LS1 1UR',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        } as Profile,
    },
    {
        user: { id: 'contractor-2', email: 'roof.master@example.com', aud: 'authenticated', created_at: new Date().toISOString(), app_metadata: {}, user_metadata: { full_name: 'David Sky' } } as any,
        profile: {
            id: 'contractor-2',
            email: 'roof.master@example.com',
            full_name: 'David Sky',
            business_name: 'Top Tier Roofing',
            user_role: 'contractor',
            account_status: 'active',
            phone: '+1 555-0202',
            address: '12 Peak Heights',
            city: 'Sheffield',
            zip_code: 'S1 1AA',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        } as Profile,
    },
    // PROPERTY MANAGERS (2)
    {
        user: { id: 'pm-1', email: 'urban.living@example.com', aud: 'authenticated', created_at: new Date().toISOString(), app_metadata: {}, user_metadata: { full_name: 'Alice Green' } } as any,
        profile: {
            id: 'pm-1',
            email: 'urban.living@example.com',
            full_name: 'Alice Green',
            user_role: 'property_manager',
            account_status: 'active',
            phone: '+1 555-0301',
            address: '101 Central Flats',
            city: 'London',
            zip_code: 'EC1 1BB',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        } as Profile,
    },
    {
        user: { id: 'pm-2', email: 'safe.stays@example.com', aud: 'authenticated', created_at: new Date().toISOString(), app_metadata: {}, user_metadata: { full_name: 'Robert White' } } as any,
        profile: {
            id: 'pm-2',
            email: 'safe.stays@example.com',
            full_name: 'Robert White',
            user_role: 'property_manager',
            account_status: 'active',
            phone: '+1 555-0302',
            address: '22 Harmony Apartments',
            city: 'Liverpool',
            zip_code: 'L1 1JR',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        } as Profile,
    },
    // CUSTOMERS (2)
    {
        user: { id: 'customer-1', email: 'jane.smith@example.com', aud: 'authenticated', created_at: new Date().toISOString(), app_metadata: {}, user_metadata: { full_name: 'Jane Smith' } } as any,
        profile: {
            id: 'customer-1',
            email: 'jane.smith@example.com',
            full_name: 'Jane Smith',
            user_role: 'customer',
            account_status: 'active',
            phone: '+1 555-0401',
            address: '14 Residential St',
            city: 'Newcastle',
            zip_code: 'NE1 1RF',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        } as Profile,
    },
    {
        user: { id: 'customer-2', email: 'peter.jones@example.com', aud: 'authenticated', created_at: new Date().toISOString(), app_metadata: {}, user_metadata: { full_name: 'Peter Jones' } } as any,
        profile: {
            id: 'customer-2',
            email: 'peter.jones@example.com',
            full_name: 'Peter Jones',
            user_role: 'customer',
            account_status: 'active',
            phone: '+1 555-0402',
            address: '99 Garden Lane',
            city: 'Glasgow',
            zip_code: 'G1 1PA',
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        } as Profile,
    },
];
